Сделана разметка главной страницы
htmlacademy-htmlcss/1049499-sedona-29 pull request #2
Opened 2020-09-13 12:19 UTC by varvara-smirnova

2020-09-13 16:24 UTC, 4err requested changes
>Не нужно вырезать изображения. Используйте вместо них заглушки, например: <img src="https://via.placeholder.com/150x100" alt="">, где 150x100 в адресе картинки — это её размер. Нарезать графику из макетов вы научитесь в четвёртом разделе.

Нужно убрать картинки на данном этапе.

Нужно разобраться с форматированием кода. У тебя сейчас он идет сплошняком. Каждый вложенный тег должен сопровождаться горизонтальным отступом в 2 или 4 пробела.
Например:
```
<section>
  <div>
    <a>Ссылка</a>
  </div>
</section>
```
Закрывающий тег находится на одной вертикали с открывающим. 
Рекомендую почитать про кодгайды и начать с кодгайда академии:
https://htmlacademy.ru/blog/academy/news/codeguide-why-what-and-how
http://codeguide.academy/html-css.html
Это позволит писать более читабельный код и избегать ошибок.

Не забывай проверять код на валидаторе, он расскажет о самых очевидных ошибках.
https://validator.w3.org/nu/
На данный момент код не проходит валидацию.

2020-09-13 16:24 UTC, 4err commented on index.html
> +<li><a href="info.html"></a>Информация</li>
Почему-то текст вне тега. Так он не будет ссылкой.

2020-09-13 16:24 UTC, 4err commented on index.html
> +<li><a href="foto.htm"></a>Фото и видео</li>
Некорректное расширение файла.

2020-09-13 16:24 UTC, 4err commented on index.html
> +<h3>Рассмотрим  причин, по которым Седона круче, чем гранд каньон!</h3>
Это не заголовки, а на самом деле просто пара рекламных абзацев.

2020-09-13 16:24 UTC, 4err commented on index.html
> +<h3>Седона - не аттракцион для туристов, там<br>течёт своя жизнь</h3>
Это тоже не заголовок, а абзац. Заголовок этого блока ты правильно выделила: Настоящий городок. Аналогично нужно исправить для остальных блоков.

2020-09-13 16:24 UTC, 4err commented on index.html
> +<h2>Седона - небольшой городок в Аризоне,<br>заслуживщий большего!</h2>
Нужно избегать использования `<br>`, здесь и далее. Их нужно добавлять в крайнем случае, когда без них никак. Пока лучше их совсем убрать. Здесь и далее.

2020-09-13 19:49 UTC, varvara-smirnova commented
Исправила

2020-09-14 06:04 UTC, 4err requested changes
Напоминаю, что не следует отправлять следующее задание до принятия предыдущего. Они слипаются вместе и невозможно принять одно без другого. 

Ссылки на изображения удалены, но не сами изображения. Их тоже нужно убрать.
Форматирование стало лучше, но все еще есть проблемы. 
Величина отступа должна быть постоянной, сейчас у тебя то один пробел, то 2. Можно включить в редакторе показ непечатываемых символов, это поможет легче отслеживать эти ошибки.
Элементы внутри одного блока должны быть на одной вертикали.
https://take.ms/p769c вот примеры ошибок.
Также обрати внимание на конец файла, у тебя почему-то футер, боди и html на одном уровне вложенности, хотя это не так.
В файле отелей ситуация лучше, но тоже есть подобные ошибки. Обрати внимание, что открывающий и закрывающий теги всегда находятся на одной вертикали, теги в одном блоке тоже всегда находятся на одной вертикали, а вложенные теги всегда имеют дополнительный отступ.

2020-09-14 06:04 UTC, 4err commented on hotels.html
> +      <li>Гостиницы</li>
Если элемент обычно является ссылкой, но при каких-то обстоятельствах нет, то нужно не убирать тег `a`, а убирать аттрибут `href=""`.
Вот так: `<a>Гостиницы</a>`
Так браузер и поисковые системы поймут, что этот элемент обычно ссылка.

2020-09-14 06:04 UTC, 4err commented on hotels.html
> +     <li>По цене</li>
Как и с гостиницей, это ссылка без href

2020-09-14 06:04 UTC, 4err commented on hotels.html
> +       <button type="button">Забронировать</button>
Это ссылки, которые ведут на соответствующие страницы.

2020-09-16 09:26 UTC, varvara-smirnova commented
На данный момент убрала файл с гостиницами.
Правильно понимаю, что как только закроется эта ветка, то я должна обновить пулреквест по второй части домашки?

2020-09-16 11:04 UTC, merged