Сетка на гридах главной страницы
htmlacademy-htmlcss/1049499-sedona-29 pull request #6
Opened 2020-10-14 11:34 UTC by varvara-smirnova

2020-10-15 05:37 UTC, 4err requested changes
https://take.ms/O8xBO Меню тоже нужно выстроить по сетке.

У тебя нет дополнительно тянущихся фонов на разных участках макета, поэтому можно и хедер и мейн и футер засунуть в один блок контейнер для центровки и задания доп стилей. Обрати внимание, что на макете будет еще тень по краям и в текущем варианте такого достичь не получится, т.к. тень будет вокруг каждого блока по отдельностти.

Скрытые заголовки можно уже скрыть чтоб не мешались, добавив класс visually-hidden и добавив свойства для скрытия со страницы ээлементов.

Старайся не использовать жестко заданную высоту для элементов. Это подходит только элементов у которых ты точно знаешь, что размер не изменится. Например, изоражения и иконки. В остальном лучше использовать `min-height` иначе получится что-то такое:
![image](https://user-images.githubusercontent.com/3590683/96081175-6ae80680-0ec1-11eb-9c38-e21c610c0c3b.png)

При превышении количества текста блок должен самомтостяельно растягиваться по вертикали.

![image](https://user-images.githubusercontent.com/3590683/96081223-8bb05c00-0ec1-11eb-8548-aac40d450e98.png)

Что-то случилось с заголовком настоящего городка, он стал огромным.

2020-10-16 05:46 UTC, 4err requested changes
Хорошо, уже лучше. 
Я не очень понял зачем нужен див `.navigation`. У тебя же есть общий `nav` контейнер, которому можно назначить все необходимые стили. 
Также т.к. теперь у нас в боди один элемент контейнер, стили висящие на боди по созданию сетки не работают, нужно перенести их на этот самый контейнер, а .page соответственно на боди. 

И последний момент - блок с фичами. 
У тебя сейчас по сути каждая строка это новый грид элемент, хотя мы можем всю эту часть превратить в грид структуру. Это сетка 3 на 4.
https://take.ms/IPRzR
Почему бы не использовать это?

2020-10-25 08:14 UTC, varvara-smirnova commented
Сетку расставила, но блоки с картинками не встают на места, не могу понять где ошибка.

2020-10-25 08:57 UTC, 4err commented
Отличная работа!
У первой картинки где-то потерялись координаты сетки:
![image](https://user-images.githubusercontent.com/3590683/97102726-eebba300-16b8-11eb-82c4-571247674982.png)
Возможно где-то опечатка.
Также у тебя сейчас высота всех строк одинаковая, хотя исходя из макета она у нас должна быть разной. Чтобы она оставалась динамической мы можем воспользоваться таким свойсвом
 `grid-template-rows: minmax(100px, 1fr);`
Указываем минимальную высоту и максимальную. Таким образом контент будет в пределах этих высот растягиваться.

2020-10-26 05:18 UTC, merged